baseURL = "https://swifte.ch"
languageCode = "en-us"
pluralizeListTitles = false
theme = "raditian-free-hugo-theme"
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
attribute = true
autoHeadingID = true
autoHeadingIDType = "github"
[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false
[[menu.footer]]
URL = "/about"
name = "About"
weight = 1
[[menu.footer]]
URL = "/support"
name = "Tech Support"
weight = "2"
[[menu.footer]]
URL = "/quickbytes"
name = "QuickBytes"
weight = "3"
[[menu.footer]]
URL = "/quickbytes/terms/how-we-work"
name = "How We Work"
weight = "4"
[[menu.footer]]
URL = "https://dropbyte.ch/#contact"
name = "Contact"
weight = "5"
[[menu.header]]
name = "Log In"
url = "https://portal.dropbyte.ch"
weight = "6"
[[menu.header]]
name = "Services"
url = "/services"
weight = 3
[[menu.header]]
URL = "/about"
name = "About"
weight = 1
[params]
about = ["about", "team", "testimonial", "contact"]
article = ["article"]
enterprise = ["enterprise-perks", "pricing-enterprise", "leads", "contact"]
form = ["form"]
googleTagManagerID = "GTM-000000"
guide = ["leads", "contact"]
homepage = ["showcase", "overview", "leads", "contact"]
premium = ["premium-perks", "pricing-premium", "leads", "contact"]
quickbytes = ["search", "leads", "contact"]
services = ["client-and-work", "extras", "pricing", "leads", "contact"]
subscribe = ["subscribe-form"]
tech_support = ["tech_header", "timeline", "pricing", "contact"]
[params.footer]
copyright = "© DropByte and "
[params.footer.radity_logo]
_2x = "img/general/design-and-code-radity@2x.png"
alt = "Design & Code - Radity"
x = "img/general/design-and-code-radity.png"
[params.logo]
text1 = "Drop"
text2 = "Byte"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"
